version: 2

updates:
  - package-ecosystem: swift
    directory: /MCPServer
    schedule:
      interval: weekly
    groups:
      swift-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      javascript-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
